# Generated by Django 5.1.3 on 2025-04-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='role',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active')], default='Pending'),
        ),
    ]
